services:
  postgres:
    image: postgres:14.0
    container_name: postgres_cont
    env_file:
      - .env
    volumes:
    - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis_cont
    restart: always
    ports:
      - 6379:6379

  airflow:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_cont
    env_file:
      - .env
    restart: always
    command: webserver
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs-volume:/opt/airflow/logs

  airflow-scheduler:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_scheduler_cont
    env_file:
      - .env
    restart: always
    command: scheduler
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs-volume:/opt/airflow/logs

  airflow-worker1:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_worker1_cont
    env_file:
      - .env
    restart: always
    command: celery worker
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs-volume:/opt/airflow/logs

  airflow-flower:
    build:
      context: .
      dockerfile: dockerfile
    container_name: airflow_flower_cont
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs-volume:/opt/airflow/logs
    env_file:
      - .env
    restart: always
    command: celery flower
    ports:
      - 5555:5555

  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - postgres

networks:
  pgnetwork:
    driver: bridge

volumes:
  database-data:
  logs-volume: